# src/config/model_config.yaml
embedding:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  batch_size: 32
  device: "cpu"
  normalize: true

retrieval:
  top_k: 5
  score_threshold: 0.7
  rerank: true
  rerank_model: "cross-encoder/ms-marco-MiniLM-L-6-v2"

generation:
  model_name: "gpt-4"
  temperature: 0.3
  max_tokens: 1000
  system_prompt: |
    You are a financial complaint analysis assistant for CrediTrust Financial.
    Provide concise, accurate answers based on the retrieved complaints.
    Highlight key patterns and suggest potential actions.

chunking:
  chunk_size: 512
  chunk_overlap: 50
  separators: ["\n\n", "\n", ". ", " ", ""]

vector_store:
  path: "data/embeddings/creditrust_faiss_index.index"

llm:
  model_name: "gpt-3.5-turbo"
  temperature: 0.3
  max_tokens: 500